#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FPMemory.Resource", IsApplication=true)]

namespace FPMemory
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int bg_black = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int bg_gray = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int bg_green = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int bg_menu_find = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int bg_menu_health = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int bg_menu_me = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int bg_menu_sports = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int bg_red = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int bg_topbar = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int bg_white = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int bg_yellow = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int div_black = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int div_gray = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int div_white = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int text_black = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int text_blue = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int text_gray = 2131034122;
			
			// aapt resource value: 0x7f050014
			public const int text_red = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int text_topbar = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int text_white = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int transparent = 2131034121;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left_click = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right_click = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int heartrate_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sports_shape = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int tab_health_bloodoxygen = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tab_health_bloodpressure = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int tab_health_heartrate = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int tab_menu_alarm = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int tab_menu_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tab_menu_find = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tab_menu_gps = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tab_menu_health = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tab_menu_me = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int tab_menu_sports = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int tab_menu_text = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int arrow_finished = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int arrow_history = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int arrow_nonfinished = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int bottomBar = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int fragmentCanvas = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080012
			public const int rbFind = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int rbHealth = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int rbMe = 2131230739;
			
			// aapt resource value: 0x7f080010
			public const int rbSports = 2131230736;
			
			// aapt resource value: 0x7f080004
			public const int rb_bloodoxygen = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int rb_bloodpressure = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int rb_heartrate = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int rg_sports_bar = 2131230721;
			
			// aapt resource value: 0x7f08000d
			public const int topBar = 2131230733;
			
			// aapt resource value: 0x7f080005
			public const int vPager = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int value_METs = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int value_sports_gait = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int value_sports_period = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int value_sports_stride = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int fg_find = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fg_health = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fg_me = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fg_sports = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SportsFinished = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int alarm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int arrow_left = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int arrow_left_pressed = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int arrow_right = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int arrow_right_pressed = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int gps = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int health_bloodoxygen_normal = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int health_bloodoxygen_pressed = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int health_bloodpressure_normal = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int health_bloodpressure_pressed = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int health_heartrate_normal = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int health_heartrate_pressed = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int heart = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ic_launcher = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ic_launcher_round = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Icon = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int pass = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int pnull = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int runner = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int tab_find_normal = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int tab_find_pressed = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int tab_health_normal = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int tab_health_pressed = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int tab_me_normal = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int tab_me_pressed = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int tab_sports_normal = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int tab_sports_pressed = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int tips_finished = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int tips_history = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int tips_nonfinished = 2130903069;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int action_settings = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int btn_pressure = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int btn_rate = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int btn_sports = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int btn_weight = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int item_sports_finished = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int item_sports_history = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int item_sports_item = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int item_sports_nonfinished = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int item_sports_period = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int item_sports_time = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int tab_health_bloodoxygen = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int tab_health_bloodpressure = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int tab_health_heartrate = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int tab_menu_find = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int tab_menu_health = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int tab_menu_me = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int tab_menu_sports = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int title_activity_weight_content = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int tv_rate_average = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int tv_rate_max = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int tv_rate_min = 2131099670;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070005
			public const int btn_recover_item = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int item_name_sports = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int item_unit_sports = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int item_value_sports = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int tab_menu_item = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int tab_menu_top = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int tb_rate_item = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int tb_sports_item = 2131165191;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
